name: Flutter Build APK & iOS

on:
  push:
    branches:
      - main # Workflow jalan setiap kali push ke branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # Menggunakan macos agar bisa build iOS sekaligus

    steps:
      - uses: actions/checkout@v4 # Update ke v4

      - name: Setup Java
        uses: actions/setup-java@v4 # Update ke v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1" # Sesuaikan dengan versi flutter abang
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # Build iOS (Tanpa sertifikat berbayar)
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      # Upload Hasil Build ke GitHub Artifacts (VERSI TERBARU V4)
      - name: Upload APK
        uses: actions/upload-artifact@v4 # KUNCI PERBAIKAN DI SINI
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4 # KUNCI PERBAIKAN DI SINI
        with:
          name: ios-build
          path: build/ios/iphoneos
